title: GRIST

google-sheet-url: https://docs.google.com/spreadsheets/d/13BgIRglusuQZhuSrMzYztKpE_tW5H9dWrM5oFxST1IA/edit?usp=sharing#gid=0

defaults:
  -
    scope:
      path: "sites"
    values:
      layout: "base"
